# Site settings
title: Beni Hassan @ Macquarie
description: 
cover: /assets/images/Kanawati-Evans-BH1-Pl-61-Beni-Hassan-3-Khnumhotep-II-Chapel-Scene-East-wall-Wall1920x.jpg
logo: /assets/images/mq-logo1.png
favicon: /assets/images/favicon.png
baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://benihassan.com" # the base hostname & protocol for your site
paginate: 5 # The number of posts to show per page on your homepage

# Social
facebook: facebook
twitter: twitter
github:  github

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: "UA-111927576-1"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: BeniHassanResearchGroup #github username
repo: BeniHassanResearchGroup.github.io #github repository
branch: master #branch
relative_source: ../hanuman/ #source directory
destination: ../hanuman-pages/ #destination directory
production_url:  http://benihassan.com/
source_url:  https://github.com/BeniHassanResearchGroup/BeniHassanResearchGroup.github.io #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - "*.sh"
